# Generated by Django 4.1 on 2022-08-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='nome',
            new_name='titulo',
        ),
    ]
