# Generated by Django 4.1 on 2022-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0002_rename_nome_video_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
    ]
